/**
 * Creating a sidebar enables you:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'index',
    },
    {
      type: 'category',
      label: 'Part I: Foundations & Robotic Systems',
      items: [
        {
          type: 'autogenerated',
          dirName: 'part1',
        },
      ],
    },
    {
      type: 'category',
      label: 'Part II: Digital Twins, Autonomy & Vision-Language-Action',
      items: [
        {
          type: 'autogenerated',
          dirName: 'part2',
        },
      ],
    },
  ],
};

export default sidebars;